##### setup report #####
configfile: "config/config.json"


# report: "report/workflow.rst"

##### load rules #####


include: "rules/deconvolution_simulation.smk"

##### target rules #####


rule all:
    input:
        expand("results/{name}_alpha_estimates.tsv", name=config["name"])